/**
 * Lazy-loads the dspbp WASM module.
 * The wasm-pkg directory is generated by:
 *   npm run build:wasm
 * which runs wasm-pack in the parent directory.
 */

export interface UpgradeMember {
  id: string
  label: string
}

export interface UpgradeGroup {
  id: string
  label: string
  members: UpgradeMember[]
}

export interface WasmModule {
  edit_blueprint(
    bp_string: string,
    replace_building: string,
    replace_item: string,
    replace_recipe: string,
    replace_both: string,
    compression_level: number
  ): string
  blueprint_info(bp_string: string): string
  upgrade_groups(): string
}

let _wasm: WasmModule | null = null
let _loadPromise: Promise<WasmModule> | null = null

export async function loadWasm(): Promise<WasmModule> {
  if (_wasm) return _wasm
  if (_loadPromise) return _loadPromise

  _loadPromise = (async () => {
    // Dynamic import so Vite treats it as an async chunk.
    // The wasm-pkg directory is generated by `npm run build:wasm`.
    const mod = await import('./wasm-pkg/dspbp.js')
    await mod.default() // calls the wasm init function
    _wasm = mod as unknown as WasmModule
    return _wasm
  })()

  return _loadPromise
}

export function getUpgradeGroups(wasm: WasmModule): UpgradeGroup[] {
  return JSON.parse(wasm.upgrade_groups()) as UpgradeGroup[]
}
